spring:
  application:
    name: r2dbc-h2-demo
  threads:
    virtual:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
logging:
  level:
    web: debug