create table product
(
--     id    UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    id   LONG AUTO_INCREMENT PRIMARY KEY,
    name  varchar(50),
    price decimal
);

CREATE TABLE trade
(
    ID   LONG AUTO_INCREMENT PRIMARY KEY,
    PRODUCT VARCHAR(255),
    PORTFOLIO VARCHAR(255),
    BOOK VARCHAR(255),
    TRADE_ID NUMBER,
    SUBMITTER_ID NUMBER,
    SUBMITTER_DEAL_ID NUMBER,
    DEAL_TYPE VARCHAR(255),
    BID_TYPE VARCHAR(255),
    CURRENT_VALUE NUMBER,
    PREVIOUS_VALUE NUMBER,
    PL1 NUMBER,
    PL2 NUMBER,
    GAIN_DX NUMBER,
    SX_PX NUMBER,
    X99_OUT NUMBER,
    batch NUMBER
);